name: 🐍 Generate Snake Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch: # manual run option

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Parvaggarwal01
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit and Push Snake SVG
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
